### ISSUE TITLE
mdbook-yml-header added to nixpkgs

### ISSUE THREAD

**Issue by pinage404** [dvogt23/mdbook-yml-header#67]
Hello,

For your information, [this project has been packaged to nixpkgs](https://github.com/NixOS/nixpkgs/pull/331176)

It is now more easier for any [Nix](https://nixos.org/) user to use your package

```sh
nix-shell --packages mdbook-yml-header
```

https://search.nixos.org/packages?channel=unstable&type=packages&query=mdbook-yml-header

https://repology.org/project/mdbook-yml-header/versions

Feel free to close this issue

**Comment by dvogt23** [comment]
Great job! Thanks a lot 🚀
